package routers

import (
	"github.com/alvinmdj/mygram-api/database"
	_ "github.com/alvinmdj/mygram-api/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/alvinmdj/mygram-api/handlers"
	"github.com/alvinmdj/mygram-api/repositories"
	"github.com/alvinmdj/mygram-api/services"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           MyGram API
// @version         1.0
// @description     This is service for MyGram.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1
func StartApp() *gin.Engine {
	r := gin.Default()

	db := database.GetDB()

	userRepo := repositories.NewUserRepo(db)
	userSvc := services.NewUserSvc(userRepo)
	userHdl := handlers.NewUserHdl(userSvc)

	v1 := r.Group("/api/v1")
	{
		// user routes
		userRouter := v1.Group("/users")
		{
			userRouter.POST("/register", userHdl.Register)
			userRouter.POST("/login", userHdl.Login)
		}
	}

	// swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
